extern const GeoLayout ice_sparkle_000_switch_opt1[];
extern const GeoLayout ice_sparkle_000_switch_opt2[];
extern const GeoLayout ice_sparkle_000_switch_opt3[];
extern const GeoLayout ice_sparkle_000_switch_opt4[];
extern const GeoLayout ice_sparkle_000_switch_opt5[];
extern const GeoLayout ice_sparkle_geo[];
extern u8 ice_sparkle_sparkle_1_rgba16[];
extern u8 ice_sparkle_sparkle_2_rgba16[];
extern u8 ice_sparkle_sparkle_3_rgba16[];
extern u8 ice_sparkle_sparkle_4_rgba16[];
extern u8 ice_sparkle_sparkle_5_rgba16[];
extern u8 ice_sparkle_sparkle_6_rgba16[];
extern Vtx ice_sparkle_000_displaylist_mesh_layer_5_vtx_0[4];
extern Gfx ice_sparkle_000_displaylist_mesh_layer_5_tri_0[];
extern Gfx mat_ice_sparkle_sparkle_1[];
extern Gfx mat_revert_ice_sparkle_sparkle_1[];
extern Gfx mat_ice_sparkle_sparkle_2[];
extern Gfx mat_revert_ice_sparkle_sparkle_2[];
extern Gfx mat_ice_sparkle_sparkle_3[];
extern Gfx mat_revert_ice_sparkle_sparkle_3[];
extern Gfx mat_ice_sparkle_sparkle_4[];
extern Gfx mat_revert_ice_sparkle_sparkle_4[];
extern Gfx mat_ice_sparkle_sparkle_5[];
extern Gfx mat_revert_ice_sparkle_sparkle_5[];
extern Gfx mat_ice_sparkle_sparkle_6[];
extern Gfx mat_revert_ice_sparkle_sparkle_6[];
extern Gfx ice_sparkle_000_displaylist_mesh_layer_5[];
extern Gfx ice_sparkle_000_displaylist_mesh_layer_5_mat_override_sparkle_2_0[];
extern Gfx ice_sparkle_000_displaylist_mesh_layer_5_mat_override_sparkle_3_1[];
extern Gfx ice_sparkle_000_displaylist_mesh_layer_5_mat_override_sparkle_4_2[];
extern Gfx ice_sparkle_000_displaylist_mesh_layer_5_mat_override_sparkle_5_3[];
extern Gfx ice_sparkle_000_displaylist_mesh_layer_5_mat_override_sparkle_6_4[];
