#include "src/game/envfx_snow.h"

const GeoLayout humbler_particle_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SCALE(LAYER_FORCE, 16384),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -15, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ASM(0, geo_move_mario_part_from_parent),
					GEO_ASM(0, geo_mario_tilt_torso),
					GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, 0, 0, humbler_particle_Torso_mesh_layer_5),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 117, 0, 0, humbler_particle_Head_mesh_layer_5),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 82, -10, 129, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(1, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, humbler_particle_Left_Arm_Color_mesh_layer_5),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, humbler_particle_Left_Forearm_skinned_mesh_layer_5),
										GEO_ANIMATED_PART(LAYER_TRANSPARENT, 75, 0, 0, humbler_particle_Left_Forearm_mesh_layer_5),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 90, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, humbler_particle_Left_Hand_DL_mesh_layer_5),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 83, -10, -129, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, humbler_particle_Right_Arm_Color_mesh_layer_5),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, humbler_particle_Right_Forearm_skinned_mesh_layer_5),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 75, 0, 0, humbler_particle_Right_Forearm_mesh_layer_5),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 90, 0, 0, NULL),
										GEO_OPEN_NODE(),
											GEO_ASM(0, geo_mario_hand_foot_scaler),
											GEO_SCALE(LAYER_FORCE, 65536),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, humbler_particle_Right_Hand_DL_mesh_layer_5),
											GEO_CLOSE_NODE(),
											GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, 102, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, humbler_particle_Left_Thigh_Color_mesh_layer_5),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, humbler_particle_Left_Leg_skinned_mesh_layer_5),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 79, 0, 0, humbler_particle_Left_Leg_mesh_layer_5),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 57, 0, 0, humbler_particle_Left_Shoe_mesh_layer_5),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, -102, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, humbler_particle_Right_Thigh_Color_mesh_layer_5),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, humbler_particle_Right_Leg_skinned_mesh_layer_5),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 79, 0, 0, humbler_particle_Right_Leg_mesh_layer_5),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 57, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(2, geo_mario_hand_foot_scaler),
									GEO_SCALE(LAYER_FORCE, 65536),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, humbler_particle_Right_Shoe_DL_mesh_layer_5),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, humbler_particle_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
